local t = require("gband.test")
local chapter = require("chapter")

local function start(g, size)
  chapter.start(g, { size = size or "40x8", env = { SHELL = "/bin/cat" }, files = { "user/colors/dusk.lua" } })
end

local function focused(g)
  return g.client("return gband.view().window")
end

local function two_marks(g)
  g.keys("alt+n")
  g.settle()
  g.keys("ctrl+space m h m escape")
  g.settle()
end

t.case("the list jumps to the line under the cursor", function(g)
  start(g)
  two_marks(g)
  t.eq(focused(g), 1)
  g.keys("ctrl+space M")
  g.settle()
  t.eq(g.client("return #gband.win.list()"), 1)
  g.expect_screenshot("two marks")
  g.keys("j")
  g.settle()
  t.eq(g.client("return gband.win.info(gband.win.list()[1]).cursor"), 2)
  g.keys("enter")
  g.settle()
  t.eq(g.client("return #gband.win.list()"), 0)
  t.eq(focused(g), 1)
end)

t.case("enter on the first line jumps to mark a", function(g)
  start(g)
  two_marks(g)
  g.keys("ctrl+space M enter")
  g.settle()
  t.eq(focused(g), 2)
end)

t.case("the list follows the marks", function(g)
  start(g)
  g.keys("ctrl+space M")
  g.settle()
  t.match(g.screen().text(), "no marks")
  g.client([[gband.cmd.run("mark", { window = 1 })]])
  g.settle()
  t.match(g.screen().text(), "a window 1 in band 1")
end)

t.case("a narrow ribbon truncates the lines", function(g)
  start(g, "16x8")
  g.keys("ctrl+space m M")
  g.settle()
  t.match(g.screen().text(), "a window 1 i…")
end)
