[package]
name = "gband-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
gband-core.workspace = true
gband-protocol.workspace = true
gband-emulator.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tui-term.workspace = true
tokio = { workspace = true, features = ["full"] }
rustix.workspace = true
anyhow.workspace = true
serde.workspace = true
gband-lua.workspace = true
notify-rust.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
gband-scratch.workspace = true
gband-server.workspace = true
gband-test-support.workspace = true
insta.workspace = true
tracing-subscriber.workspace = true
vt100.workspace = true
mlua.workspace = true
