local t = require("gband.test")

t.case("the direct style's mode letter and key list title", function(g)
  g.start({ keystyle = "direct" })
  g.wait_text("$")
  g.keys("ctrl+space")
  g.settle()
  t.match(g.screen().row(0), "^P")
  g.keys("?")
  g.settle()
  t.match(g.screen().text(), "prefix keys")
  g.expect_screenshot("direct")
end)
