local t = require("gband.test")

t.case("the chooser fits beside the default sidebar on the first start", function(g)
  g.start({ keystyle = false })
  g.wait_text("$")
  g.keys("down up")
  g.settle()
  t.eq(g.client("return #gband.win.list()"), 1)
  t.match(g.screen().row(0), "^I")
  t.match(g.screen().row(10), "^ │ +┌key style  enter choose  esc later.-┐$")
  t.match(g.screen().row(11), "^ │ +│modal   C%-space enters a mode, keys repeat until Escape│")
  t.match(g.screen().row(12), "^ │ +│direct  C%-space then one key per action, back to typing│")
  t.eq(g.screen().cell(10, 12).char, "┌")
  t.eq(g.screen().cell(13, 68).char, "┘")
  g.expect_screenshot("first-start")
  g.keys("escape")
  g.wait(function()
    return g.client("return #gband.win.list()") == 0
  end)
  g.keys("ctrl+space")
  g.settle()
  t.match(g.screen().row(0), "^N")
end)

t.case("the direct style's mode letter and key list title", function(g)
  g.start({ keystyle = "direct" })
  g.wait_text("$")
  g.keys("ctrl+space")
  g.settle()
  t.match(g.screen().row(0), "^P")
  g.keys("?")
  g.settle()
  t.match(g.screen().text(), "prefix keys")
  g.expect_screenshot("direct")
end)
