local t = require("gband.test")

local function settings_open(g)
  g.wait(function(screen)
    return screen.text():find("┌settings", 1, true) and "open"
  end)
end

t.case("the settings window beside the default sidebar on the first start", function(g)
  g.start({ keystyle = false, theme = false })
  g.wait_text("$")
  settings_open(g)
  g.settle()
  t.match(g.screen().row(0), "^I")
  t.match(g.screen().row(9), "^ │ +┌settings.-┐$")
  t.match(g.screen().row(10), "^ │ +│theme    default +│")
  t.match(g.screen().row(11), "^ │ +│sidebar  on +│")
  t.match(g.screen().row(12), "^ │ +│keys     modal +│")
  t.eq(g.screen().cell(9, 25).char, "┌")
  t.eq(g.screen().cell(13, 55).char, "┘")
  g.keys("j k")
  g.settle()
  g.expect_screenshot("first start")
end)

t.case("the theme list beside the default sidebar", function(g)
  g.start({})
  g.wait_text("$")
  g.keys("ctrl+space s")
  settings_open(g)
  g.keys("enter")
  g.wait_text("┌theme")
  g.settle()
  t.eq(g.screen().cell(3, 29).char, "┌")
  t.eq(g.screen().cell(19, 50).char, "┘")
  t.match(g.screen().row(4), "│default +│")
  t.match(g.screen().row(18), "│vesper +│")
  g.expect_screenshot("theme list")
end)

t.case("a gruvbox frame", function(g)
  g.start({ theme = "gruvbox" })
  g.wait_text("$")
  g.run("printf '\\033[31m%s\\033[0m\\n' red")
  g.wait_text("$ printf")
  g.wait(function(screen)
    return screen.text():find("│red", 1, true) and "printed"
  end)
  g.settle()
  t.eq(g.screen().cell(0, 0).bg, "#3c3836")
  g.expect_screenshot("gruvbox")
end)
