local t = require("gband.test")
local chapter = require("chapter")

local function start(g)
  chapter.start(g, { size = "40x8", env = { SHELL = "/bin/cat" }, files = { "user/colors/dusk.lua" } })
end

t.case("shows the bar", function(g)
  start(g)
  t.eq(g.client([[return gband.bar.info("mark").col]]), 1)
  t.match(g.screen().row(0), "^I ╭")
  g.keys("alt+n")
  g.settle()
  g.keys("ctrl+space m escape")
  g.settle()
  t.match(g.screen().row(0), "^Ia╭")
  g.keys("alt+h")
  g.settle()
  t.match(g.screen().row(0), "^I ╭")
  g.keys("alt+l")
  g.settle()
  g.expect_screenshot("two windows")
end)

t.case("the bar draws the mark in the Mark group", function(g)
  start(g)
  g.keys("ctrl+space m escape")
  g.settle()
  t.eq(g.screen().cell(0, 1).char, "a")
  t.eq(g.screen().cell(0, 1).fg, 3)
  t.ok(g.screen().cell(0, 1).bold, "the mark is bold")
end)

t.case("unmarking clears the bar", function(g)
  start(g)
  g.keys("ctrl+space m")
  g.settle()
  t.match(g.screen().row(0), "^Na")
  g.keys("m escape")
  g.settle()
  t.match(g.screen().row(0), "^I ╭")
end)
