gband.plugin("gband.keylist")
gband.plugin("gband.prompt")

local set = gband.keymap.set
local action = gband.action

gband.keymap.mode("prefix", { label = "navigation" })

local function interactive()
  gband.keymap.enter("root")
end

set("prefix", "h", action.focus_column_left, { desc = "focus the column to the left" })
set("prefix", "l", action.focus_column_right, { desc = "focus the column to the right" })
set("prefix", "j", action.focus_window_down, { desc = "focus the window below" })
set("prefix", "k", action.focus_window_up, { desc = "focus the window above" })
set("prefix", "u", action.focus_band_down, { desc = "view the band below" })
set("prefix", "i", action.focus_band_up, { desc = "view the band above" })
set("prefix", "c", action.center_column, { desc = "center the focused column" })
set("prefix", "n", function()
  action.open_window()
  interactive()
end, { desc = "open a window" })
set("prefix", "q", action.close_window, { desc = "close the window" })
set("prefix", "[", action.consume_or_expel_left, { desc = "consume or expel the window to the left" })
set("prefix", "]", action.consume_or_expel_right, { desc = "consume or expel the window to the right" })
set("prefix", "r", action.cycle_column_width, { desc = "cycle the width of the window's column" })
set("prefix", "f", action.toggle_full_width, { desc = "toggle full width of the window's column" })
set("prefix", "-", action.shrink_column_width, { desc = "shrink the width of the window's column" })
set("prefix", "=", action.grow_column_width, { desc = "grow the width of the window's column" })
set("prefix", "_", action.shrink_window_height, { desc = "shrink the height of the window" })
set("prefix", "+", action.grow_window_height, { desc = "grow the height of the window" })
set("prefix", "R", action.reset_window_height, { desc = "reset the height of the window" })
set("prefix", "v", action.toggle_window_floating, { desc = "float or tile the window" })
set("prefix", "V", action.switch_focus_floating_tiled, { desc = "switch focus between floating and tiled windows" })
set("prefix", "ctrl+h", action.move_column_left, { desc = "move the column or floating window to the left" })
set("prefix", "ctrl+l", action.move_column_right, { desc = "move the column or floating window to the right" })
set("prefix", "ctrl+j", action.move_window_down, { desc = "move the window down" })
set("prefix", "ctrl+k", action.move_window_up, { desc = "move the window up" })
set("prefix", "ctrl+left", action.move_column_left, { desc = "move the column or floating window to the left" })
set("prefix", "ctrl+right", action.move_column_right, { desc = "move the column or floating window to the right" })
set("prefix", "ctrl+down", action.move_window_down, { desc = "move the window down" })
set("prefix", "ctrl+up", action.move_window_up, { desc = "move the window up" })
set("prefix", "?", action["keylist.open"], { desc = "list the keys" })
set("prefix", ":", action["prompt.open"], { desc = "run Lua" })
set("prefix", "D", action.detach, { desc = "detach" })
set("prefix", "escape", interactive, { desc = "interactive mode" })
set("prefix", "enter", interactive, { desc = "interactive mode" })
set("prefix", "left", action.focus_column_left, { desc = "focus the column to the left" })
set("prefix", "right", action.focus_column_right, { desc = "focus the column to the right" })
set("prefix", "down", action.focus_window_down, { desc = "focus the window below" })
set("prefix", "up", action.focus_window_up, { desc = "focus the window above" })
set("prefix", "prefix", function()
  action.send_prefix()
  interactive()
end, { desc = "send the prefix key" })
