gband.hl.set("Bar", { bg = "black" })
gband.hl.set("SidebarMode", { fg = "blue", bold = true })
gband.hl.set("SidebarBand", { fg = "bright_black" })
gband.hl.set("SidebarBandActive", { fg = "bright_white", bold = true })
gband.hl.set("SidebarError", { fg = "red", bold = true })
gband.hl.set("KeyListKey", { fg = "blue", bold = true })
gband.hl.set("KeyListMuted", { fg = "bright_black" })
gband.hl.set("PluginWindow", { fg = "white", bg = "black" })
gband.hl.set("PluginWindowBorder", { fg = "bright_black", bg = "black" })
gband.hl.set("PluginWindowTitle", { fg = "blue", bg = "black", bold = true })
gband.hl.set("PluginWindowCursorLine", { fg = "black", bg = "blue" })
gband.hl.set("PromptCursor", { reverse = true })
gband.hl.set("SettingsLabel", { fg = "bright_black" })
gband.hl.set("WindowBorder", { fg = "bright_black" })
gband.hl.set("WindowBorderFocused", { fg = "blue", bold = true })
gband.hl.set("ErrorBanner", { fg = "red", reverse = true })
