[package]
name = "gband-lua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
gband-core.workspace = true
gband-protocol.workspace = true
mlua.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
unicode-width.workspace = true

[dev-dependencies]
gband-scratch.workspace = true
tracing-subscriber.workspace = true
