local t = require("gband.test")
local chapter = require("chapter")

local function start(g, opts)
  opts = opts or {}
  opts.size = "40x8"
  opts.env = { SHELL = "/bin/cat" }
  chapter.start(g, opts)
end

local function focused(g)
  return g.client("return gband.view().window")
end

t.case("a jump returns to the marked window", function(g)
  start(g)
  g.keys("alt+n")
  g.settle()
  g.keys("alt+n")
  g.settle()
  t.eq(g.client("return #gband.layout().bands[1].columns"), 3)
  g.keys("alt+h alt+h")
  g.settle()
  t.eq(focused(g), 1)
  g.keys("ctrl+space m escape alt+l alt+l")
  g.settle()
  t.eq(focused(g), 3)
  g.keys("ctrl+space ' a")
  g.settle()
  t.eq(focused(g), 1)
  t.eq(g.client("return gband.keymap.current_table()"), "root")
end)

t.case("a jump views the band of the marked window", function(g)
  start(g)
  g.keys("ctrl+space m u")
  g.settle()
  t.eq(g.client("return gband.view().band"), 2)
  g.keys("' a")
  g.settle()
  t.eq(g.client("return gband.view().band"), 1)
  t.eq(focused(g), 1)
end)

t.case("a letter without a mark rings the bell", function(g)
  start(g)
  g.keys("ctrl+space ' b")
  g.settle()
  t.eq(g.bells(), 1)
end)

t.case("prefix g views the first band", function(g)
  start(g)
  g.keys("ctrl+space u")
  g.settle()
  t.eq(g.client("return gband.view().band"), 2)
  g.keys("g")
  g.settle()
  t.eq(g.client("return gband.view().band"), 1)
end)

t.case("a mark names the window", function(g)
  start(g, { window_titles = true })
  g.keys("ctrl+space m escape")
  g.settle()
  t.eq(g.client("return gband.layout().bands[1].columns[1].windows[1].manual_name"), "mark a")
  t.match(g.screen().row(0), "mark a")
  g.expect_screenshot()
end)
