require("gband.hl")
require("gband.palette")
require("gband.colorscheme")
require("gband.bar")
require("gband.win")
require("gband.settings")
require("gband.keystyle")
require("gband.colorscheme").start()
