[package]
name = "gband-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
gband-core.workspace = true
gband-protocol.workspace = true
gband-emulator.workspace = true
gband-lua.workspace = true
portable-pty.workspace = true
tokio = { workspace = true, features = ["full"] }
rustix.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
gband-scratch.workspace = true
gband-test-support.workspace = true
