[package]
name = "gband-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
gband-core.workspace = true
gband-protocol.workspace = true
portable-pty.workspace = true
vt100.workspace = true
tokio.workspace = true
mlua.workspace = true
rustix.workspace = true
notify.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
